### ISSUE TITLE
1 warning generated. error: unableToFind(tool: "swift-autolink-extract")?

### ISSUE THREAD

**Issue by johnburkey** [buttaface/swift-android-sdk#50]
Hey!

Just tried your release build and got this error.   Any idea what its about?

I did see this:

https://forums.swift.org/t/swift-autolink-extract-and-swift-indent-missing-from-recent-toolchains/33943

**Comment by johnburkey** [comment]
Oh and im on Apple Silicon Xcode Version 13.4 (13F17a) tools

**Comment by buttaface** [comment]
That sounds familiar: do the Xcode tools come with `swift-autolink-extract`, which is just a symbolic link to `swift-frontend` in the Linux toolchain?

I suggest you try cross-compiling simple test executables first, [as shown here in the Android doc](https://github.com/apple/swift/blob/main/docs/Android.md#2-compiling-helloswift-to-run-on-an-android-device), but simply replacing the resource directory path with the one from my prebuilt SDK, ie `swift-5.6-android-aarch64-24-sdk/usr/lib/swift`.

That would be the easiest way to check if cross-compilation is working for your toolchain/SDK combo.

**Comment by buttaface** [comment]
Closing since there's no response, feel free to fill in later.
