### ISSUE TITLE
Java not able to open .so file generated by this project

### ISSUE THREAD

**Issue by hjuraev** [buttaface/swift-android-sdk#74]
I was able to compile my project using this SDK. It created .so files that should be compatible with JNI. But I'm facing a different problem, the android project compiles successfully, but when the java code is trying to load a .so file, I'm getting this error.

java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~1ftAMe1LzrCJsXmWFBcigA==/nexus.us.swift_native-7raIURWcYa11TdtF8jLtCg==/base.apk!/lib/arm64-v8a/libdispatch.so" (new hash type from the future?)

Any thoughts on this?

**Comment by buttaface** [comment]
Others have reported this issue, [can you check if their reported solution fixes it for you too](https://github.com/buttaface/swift-android-sdk/issues/67#issuecomment-1227460068)? I don't use Gradle and the SDK, so I'm not familiar with what that does.

**Comment by hjuraev** [comment]
Yes, you are right.
It was resolved before.

packagingOptions {
    doNotStrip "*/arm64-v8a/*.so"
    doNotStrip "*/armeabi-v7a/*.so"
    doNotStrip "*/x86_64/*.so"
}
This little snippet in gradle can solve the problem.
Closing this issue.
Thanks
